[package]
name = "purecode"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive", "env"] }
colored = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
walkdir = "2.4"
glob = "0.3"
